name: litpie
description: A New Social Media Platform.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  url_launcher: ^6.0.0
  country_code_picker: ^2.0.1
  intl:
  shared_preferences: ^2.0.5
  provider: ^6.0.2
  firebase_core: ^1.0.3
  firebase_auth: ^3.3.9
  firebase_messaging: ^11.2.8
  firebase_database: ^9.0.8
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  cached_network_image: ^3.0.0
  photo_view: ^0.13.0
  image_cropper: ^1.5.0
  image_picker: ^0.8.4+1
  video_player: ^2.1.14
  location: ^4.3.0
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  permission_handler: ^9.2.0
  video_compress: ^3.1.0
  shimmer: ^2.0.0
  app_settings: ^4.1.1
  carousel_slider: ^4.0.0
  easy_localization: ^3.0.0
  percent_indicator: ^3.0.1
  connectivity_plus: ^2.2.1
  swipe_to: ^1.0.2
  flutter_slidable: ^0.6.0-nullsafety.0
  ntp: ^2.0.0
  google_mobile_ads: ^1.1.0
  firebase_analytics: ^9.1.2
  app_tracking_transparency: ^2.0.2+1
  flutter_local_notifications: ^9.3.3
  audioplayers: ^0.20.1
  flutter_app_badger: ^1.3.0
  share: ^2.0.4
  uuid: ^3.0.6
  file_picker: ^4.5.0
  http: ^0.13.4
  dropdown_button2: ^1.1.0
  readmore: ^2.1.0
  badges: ^2.0.2








dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.5

flutter_native_splash:
  image: "assets/images/splashlogo.png"
  color: "ffffff"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/auth/
    - assets/images/
    - assets/translation/
    - assets/tone/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Handlee
      fonts:
        - asset: assets/fonts/Handlee-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
